[build]
  publish = "/"

[build.processing]
  skip_processing = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
